Module6 task2
htmlacademy-ecmascript/159210-big-trip-21 pull request #11
Opened 2023-10-02 19:28 UTC by slipfly

2023-10-02 19:32 UTC, slipfly commented on src/view/event-edit-view.js
> +    //даты сохраняются некорректно
здесь не могу распарсить дату корректно

2023-10-04 15:28 UTC, arcticneko requested changes

2023-10-04 15:28 UTC, arcticneko commented on src/view/event-edit-view.js
> +      isDestination: evt.target.value !== '',
это поле, по сути, дублирует поле ```destination```, по этому без него можно обойтись

сейчас править большого смысла уже нет, но на будущее стоит учитывать

2023-10-04 15:28 UTC, arcticneko commented on src/view/event-edit-view.js
> +      const smth = EVENT_TYPES.filter((item) =>
получилось сложно. давай подумаем, как можно упросить

2023-10-04 15:28 UTC, arcticneko commented on src/view/event-header-view.js
> +      date: dayjs(userDate).format(DATE_FORMAT.dateOnlyFormat)
нужно подумать над использованием единого формата хранения даты и преобразования его под наши потребности уже во view компоненте

2023-10-04 15:28 UTC, arcticneko approved these changes

2023-10-04 15:29 UTC, arcticneko commented
апрувнул, вопросы из ПРа можно будет разобрать в следующем ПРе

2023-10-04 15:29 UTC, merged